[server]
menuItems = [
    {"name": "ğŸ  Inicio", "path": "/"},
    {"name": "ğŸ“‹ Asignador", "path": "/Asignador"},
    {"name": "âš™ï¸ Generador Demanda", "path": "/Generador_Demanda"},
    {"name": "ğŸ“Š Informes", "path": "/Informes"}
]
